--- pscheduler.orig/pscheduler/limitprocessor/limitprocessor.py	2021-08-26 19:45:22.316574176 +0100
+++ pscheduler/pscheduler/limitprocessor/limitprocessor.py	2021-08-30 18:22:58.312891903 +0100
@@ -262,7 +262,7 @@
             return self._process(task, hints, rewrite, prioritize)
         except Exception as ex:
             diags = 'Failed to process limits: processor threw an exception.\n\n' \
-                    f'{formatted_exception(ex)}\n\n' \
+                    '{!r}'.formatted_exception(ex)+'\n\n' \
                     'Please report this as a bug.'
             return (False, [], diags, task, None)
 
